trigger:
- master
- v2

variables:
  buildConfiguration: 'Release'
  framework: 'net5.0'

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: azure/build.yml

- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: azure/build.yml

- job: MacOS
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - template: azure/build.yml

# For now, we do not want to deploy the docs from the v2 branch
#- job: DeployDocs
#  dependsOn:
#  - Windows
#  condition: succeeded()
#  pool:
#    vmImage: 'windows-2019'
#  steps:
#  - template: azure/docs.yml