trigger:
- master
- v1.x

variables:
  buildConfiguration: 'Release'
  framework: 'netcoreapp3.1'

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: azure/build.yml

- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - template: azure/build.yml

- job: MacOS
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - template: azure/build.yml

#- job: DeployDocs
#  dependsOn:
#  - Windows
#  condition: succeeded()
#  pool:
#    vmImage: 'windows-2019'
#  steps:
#  - template: azure/docs.yml